# Generated by Django 5.2.6 on 2025-09-24 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autores',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='leitor',
            options={'verbose_name': 'Leitor', 'verbose_name_plural': 'Leitores'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterField(
            model_name='autores',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade do autor'),
        ),
        migrations.AlterField(
            model_name='autores',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do autor'),
        ),
        migrations.AlterField(
            model_name='autores',
            name='site',
            field=models.CharField(max_length=50, verbose_name='Site do autor'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da cidade'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.CharField(max_length=50, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade da editora'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome da editora'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.CharField(max_length=50, verbose_name='Site da editora'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF do leitor'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email do leitor'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do leitor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autores', verbose_name='Autor do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(verbose_name='Data de publicação do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.editora', verbose_name='Editora do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.BooleanField(verbose_name='Status do livro'),
        ),
    ]
